
const DB='bukhTaavarProV2';
const defaultState={currentUser:null,users:[],closed:false,results:null,events:[{id:'naadam2026',name:'Улсын баяр наадам 2026',status:'Таавар авч байна'}],wrestlers:['О.Хангай','Б.Орхонбаяр','П.Бүрэнтөгс','Н.Батсуурь','Ц.Содномдорж','Р.Пүрэвдагва','М.Бадарч','Б.Гончигдамба','Э.Оюунболд','Д.Анар','Аймгийн арслан түрүүлэхгүй'],predictions:[],settings:{points:{champion:100,runner:70,semi:40,quarter:20,province:30,title:30,combo:120}},adminPin:'1234'};
let S=load();let tab='home';
function load(){let s=localStorage.getItem(DB);return s?JSON.parse(s):structuredClone(defaultState)}
function save(){localStorage.setItem(DB,JSON.stringify(S))}
function $(q){return document.querySelector(q)}
function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36)}
function me(){return S.users.find(u=>u.id===S.currentUser)}
function render(){document.getElementById('app').innerHTML=`<div class="wrap">${screen()}</div>${nav()}`;bind()}
function nav(){let items=[['home','Нүүр'],['predict','Таавар'],['mine','Минийх'],['board','Чансаа'],['admin','Админ']];return `<div class="tabs">${items.map(i=>`<button class="${tab==i[0]?'active':''}" onclick="tab='${i[0]}';render()">${i[1]}</button>`).join('')}</div>`}
function screen(){if(tab==='home')return home();if(tab==='predict')return predict();if(tab==='mine')return mine();if(tab==='board')return board();if(tab==='admin')return admin();}
function authBox(){let u=me(); if(u)return `<div class="row"><div class="avatar">${u.name[0]||'Б'}</div><div><b>${u.name}</b><div class="muted small">${u.phone} · ${u.score||0} оноо</div></div><button class="secondary" onclick="logout()">Гарах</button></div>`;return `<div class="card"><h2>Бүртгүүлэх / Нэвтрэх</h2><p class="muted">Одоогийн хувилбар localStorage дээр ажиллана. Дараагийн шатанд Firebase OTP утасны баталгаажуулалт холбоно.</p><div class="grid"><div class="span6"><input id="name" placeholder="Нэр"></div><div class="span6"><input id="phone" placeholder="Утасны дугаар"></div><div class="span12"><button onclick="login()">Нэвтрэх / бүртгүүлэх</button></div></div></div>`}
function home(){let u=me();return `<div class="hero"><h1>Бөх Таавар Pro</h1><p class="muted">Монгол бөхийн оноотой тааврын систем. Бодит мөнгөний бооцоо биш — таамаг, оноо, чансаа, шагналын лиг.</p>${authBox()}</div><h2>Системийн боломж</h2><div class="grid"><div class="card span4"><div class="score">${S.users.length}</div><b>Бүртгэлтэй хэрэглэгч</b><p class="muted">Олон хүн орж оноогоор өрсөлдөнө.</p></div><div class="card span4"><div class="score">${S.predictions.length}</div><b>Нийт таавар</b><p class="muted">Таавар хаагдахаас өмнө засаж болно.</p></div><div class="card span4"><div class="score">${S.closed?'Хаалттай':'Нээлттэй'}</div><b>Тааврын төлөв</b><p class="muted">Админ хүссэн үед хаана.</p></div></div><div class="notice" style="margin-top:14px">Энэ v2 нь бүртгэл, оноо, админ, үр дүн оруулах, автомат оноо бодох үндсэн логиктой.</div>`}
function predict(){if(!me())return authBox();let p=S.predictions.find(x=>x.userId===S.currentUser)||{};let opts=S.wrestlers.map(w=>`<option ${p.champion==w?'selected':''}>${w}</option>`).join('');let opts2=S.wrestlers.map(w=>`<option ${p.runner==w?'selected':''}>${w}</option>`).join('');return `<h2>Таавар өгөх</h2>${S.closed?'<div class="notice">Таавар хаагдсан байна. Одоо засах боломжгүй.</div>':''}<div class="grid"><div class="card span6"><label>Түрүүлэх бөх</label><select id="champion">${opts}</select><br><br><label>Үзүүрлэх бөх</label><select id="runner">${opts2}</select><br><br><label>Аль аймгийн бөх түрүүлэх вэ?</label><input id="province" value="${p.province||''}" placeholder="Жишээ: Ховд, Архангай"><br><br><label>Аль цолны бөх шөвгөрөх вэ?</label><select id="title"><option ${p.title==='Аварга'?'selected':''}>Аварга</option><option ${p.title==='Арслан'?'selected':''}>Арслан</option><option ${p.title==='Заан'?'selected':''}>Заан</option><option ${p.title==='Начин'?'selected':''}>Начин</option><option ${p.title==='Аймгийн цолтон'?'selected':''}>Аймгийн цолтон</option></select></div><div class="card span6"><b>Шөвгийн 4</b>${multi('semi',p.semi||[])}<br><b>Шөвгийн 8</b>${multi('quarter',p.quarter||[])}</div><div class="span12"><button ${S.closed?'disabled':''} onclick="savePrediction()">Таавар хадгалах</button></div></div>`}
function multi(name,arr){return S.wrestlers.slice(0,10).map(w=>`<label class="choice"><input type="checkbox" name="${name}" value="${w}" ${arr.includes(w)?'checked':''}>${w}</label>`).join('')}
function mine(){let u=me();if(!u)return authBox();let p=S.predictions.find(x=>x.userId===u.id);return `<h2>Миний мэдээлэл</h2><div class="grid"><div class="card span4"><div class="avatar">${u.name[0]}</div><h2>${u.name}</h2><div class="score">${u.score||0}</div><div class="muted">нийт оноо</div></div><div class="card span8"><h2>Миний таавар</h2>${p?predHtml(p):'<p class="muted">Та таавар өгөөгүй байна.</p>'}</div></div>`}
function predHtml(p){return `<p><b>Түрүү:</b> ${p.champion||'-'}</p><p><b>Үзүүр:</b> ${p.runner||'-'}</p><p><b>Шөвгийн 4:</b> ${(p.semi||[]).join(', ')}</p><p><b>Шөвгийн 8:</b> ${(p.quarter||[]).join(', ')}</p><p><b>Аймаг:</b> ${p.province||'-'} · <b>Цол:</b> ${p.title||'-'}</p><p class="muted small">Оноо бодсон дүн: ${p.calculatedScore||0}</p>`}
function board(){let rows=[...S.users].sort((a,b)=>(b.score||0)-(a.score||0)).map((u,i)=>`<tr><td>${i+1}</td><td>${u.name}</td><td>${u.phone}</td><td><b>${u.score||0}</b></td></tr>`).join('');return `<h2>Чансааны самбар</h2><div class="card"><table class="table"><tr><th>#</th><th>Нэр</th><th>Утас</th><th>Оноо</th></tr>${rows||'<tr><td colspan="4">Одоогоор хэрэглэгч алга.</td></tr>'}</table></div>`}
function admin(){return `<h2>Админ самбар</h2><div class="grid"><div class="card span6"><h2>Нэвтрэх PIN</h2><input id="pin" placeholder="PIN: 1234"><br><br><button onclick="adminLogin()">Админ эрх нээх</button><p class="muted small">Жинхэнэ хувилбарт PIN биш Firebase Admin Role хэрэглэнэ.</p></div><div class="card span6"><h2>Онооны дүрэм</h2>${Object.entries(S.settings.points).map(([k,v])=>`<p>${k}: <b>${v}</b></p>`).join('')}</div></div><div id="adminPanel">${sessionStorage.admin==='1'?adminPanel():''}</div>`}
function adminPanel(){let r=S.results||{};let opts=S.wrestlers.map(w=>`<option ${r.champion==w?'selected':''}>${w}</option>`).join('');let opts2=S.wrestlers.map(w=>`<option ${r.runner==w?'selected':''}>${w}</option>`).join('');return `<div class="grid" style="margin-top:14px"><div class="card span6"><h2>Тааврын төлөв</h2><p>Одоо: <b>${S.closed?'Хаалттай':'Нээлттэй'}</b></p><button class="secondary" onclick="toggleClose()">${S.closed?'Нээх':'Хаах'}</button></div><div class="card span6"><h2>Бөх нэмэх</h2><input id="newW" placeholder="Бөхийн нэр"><br><br><button onclick="addWrestler()">Нэмэх</button></div><div class="card span12"><h2>Үр дүн оруулах</h2><div class="grid"><div class="span6"><label>Түрүү</label><select id="rChampion">${opts}</select></div><div class="span6"><label>Үзүүр</label><select id="rRunner">${opts2}</select></div><div class="span6"><label>Аймаг</label><input id="rProvince" value="${r.province||''}"></div><div class="span6"><label>Цол</label><select id="rTitle"><option>Аварга</option><option>Арслан</option><option>Заан</option><option>Начин</option><option>Аймгийн цолтон</option></select></div><div class="span6"><b>Шөвгийн 4</b>${multi('rSemi',r.semi||[])}</div><div class="span6"><b>Шөвгийн 8</b>${multi('rQuarter',r.quarter||[])}</div><div class="span12"><button onclick="saveResults()">Үр дүн хадгалж оноо бодох</button></div></div></div></div>`}
function bind(){}
function login(){let name=$('#name').value.trim(),phone=$('#phone').value.trim();if(!name||!phone)return alert('Нэр, утсаа оруулна уу');let u=S.users.find(x=>x.phone===phone);if(!u){u={id:uid(),name,phone,score:0,createdAt:new Date().toISOString()};S.users.push(u)}S.currentUser=u.id;save();render()}
function logout(){S.currentUser=null;save();render()}
function checks(n){return [...document.querySelectorAll(`input[name=${n}]:checked`)].map(x=>x.value)}
function savePrediction(){if(S.closed)return alert('Таавар хаагдсан');let p=S.predictions.find(x=>x.userId===S.currentUser);if(!p){p={id:uid(),userId:S.currentUser};S.predictions.push(p)}Object.assign(p,{champion:$('#champion').value,runner:$('#runner').value,province:$('#province').value.trim(),title:$('#title').value,semi:checks('semi').slice(0,4),quarter:checks('quarter').slice(0,8),updatedAt:new Date().toISOString()});save();alert('Таавар хадгалагдлаа');tab='mine';render()}
function adminLogin(){if($('#pin').value===S.adminPin){sessionStorage.admin='1';render()}else alert('PIN буруу')}
function toggleClose(){S.closed=!S.closed;save();render()}
function addWrestler(){let v=$('#newW').value.trim();if(v&&!S.wrestlers.includes(v))S.wrestlers.push(v);save();render()}
function saveResults(){S.results={champion:$('#rChampion').value,runner:$('#rRunner').value,province:$('#rProvince').value.trim(),title:$('#rTitle').value,semi:checks('rSemi').slice(0,4),quarter:checks('rQuarter').slice(0,8),savedAt:new Date().toISOString()};calculateScores();save();alert('Оноо бодогдлоо');tab='board';render()}
function calculateScores(){let P=S.settings.points,R=S.results;S.users.forEach(u=>u.score=0);S.predictions.forEach(p=>{let sc=0;if(p.champion===R.champion)sc+=P.champion;if(p.runner===R.runner)sc+=P.runner;(p.semi||[]).forEach(x=>{if((R.semi||[]).includes(x))sc+=P.semi});(p.quarter||[]).forEach(x=>{if((R.quarter||[]).includes(x))sc+=P.quarter});if((p.province||'').toLowerCase()===(R.province||'').toLowerCase())sc+=P.province;if(p.title===R.title)sc+=P.title;if(p.champion===R.champion&&p.runner===R.runner&&(p.semi||[]).filter(x=>(R.semi||[]).includes(x)).length>=4)sc+=P.combo;p.calculatedScore=sc;let u=S.users.find(x=>x.id===p.userId);if(u)u.score+=sc})}
window.addEventListener('load',()=>{render(); if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})});
